gctools-outilsgc/aurora-website

- src/components/languageSwitch.js
I changed the LanguageSwitcher into a toggle between english and french like in the mockup.
> Language switcher

- src/components/header.js
- src/components/layout.scss
when viewing the site on a mobile device the main menu in the header will scroll horizontally. To do: move the sass to another location test on phone browsers.
> header mobile style

- src/components/header.js
- src/components/languageSwitch.js
- src/components/layout.js
- src/components/sidenav.js
- src/pages/index.js
- src/templates/mdTemplate.js
- src/utils/custom-styles.scss
Adding some basic tweaks based on Axe analysis.
> start of a11y tweaks regions + lang toggle + skip link

- package.json
- src/layouts/layout.js
- src/pages/index.js
Making small style tweaks to the index page. Also updated the develop script for those not developing through localhost.
Please let me know what other tweaks need to be made.
> index style changes + updated develop script

- src/docs/fr/component/balises puces et pilules.md
- src/docs/fr/component/boutons.md
- src/docs/fr/component/couleur.md
- src/docs/fr/component/formulaires saisies des boutons.md
- src/docs/fr/component/formulaires saisies textuelles.md
- src/docs/fr/component/indicateurs d'etat.md
- src/docs/fr/component/liens.md
- src/docs/fr/component/messagerie du systeme.md
- src/docs/fr/component/seperateur ou regle.md
- src/docs/fr/component/televersement des fichiers.md
- src/docs/fr/component/typographie.md
- src/docs/fr/content/mise en forme du contenu.md
- src/docs/fr/data/donnees_ apercu.md
- src/docs/fr/data/donnees_ graphiques lineaires.md
- src/docs/fr/data/donnes_ les legendes et infobulles.md
- src/docs/fr/overview/foire-aux-questions.md
- src/docs/fr/overview/nouveautes.md
Minor updates to FR documentation based on Sabrina's comparative review. 
Edited for consistency, language and spelling/grammatical errors.
> French review

- src/docs/en/overview/future-updates.md
- src/docs/fr/overview/mises a jour.md
Added future updates pages to overview section in both EN and FR
> Added future updates pages

- CONTRIBUTING.md
- LICENSE
- README.md
> Add MIT LICENCE and CONTRIBUTING files

- src/docs/en/component/colour.md
- src/docs/en/content/system vocabulary.md
- src/docs/fr/component/couleur.md
- src/docs/fr/content/vocabulaire du systeme.md
* Fixed broken typography links on Colour page
* Added "Submit" to system vocabulary
> Content fixes

- src/docs/en/component/typography.md
- src/docs/fr/component/typographie.md
Doesn't close any issues, but something small I've gotten questions about and decided to add. :)
> Typography addition

- src/docs/en/component/badges.md
- src/docs/en/component/button-inputs.md
- src/docs/fr/component/badges.md
- src/docs/fr/component/formulaires saisies des boutons.md
- src/utils/custom-styles.scss
Modified badge page to include more examples of badges. Also changed custom checkbox/radio button styles to match written style. Also the switch element is now accessible.
Closes #91 
Closes #88
> Changes badges page and button inputs styles

- src/docs/en/component/colour.md
- src/docs/fr/component/couleur.md
* Added Canada.ca colour palette to our list of available palettes
* Added descriptions to each palette
* Fixed headings structure on colours page
* Done in both EN and FR
> Changes to Colour page

- src/components/DocumentationTabs.js
- src/docs/en/component/components.md
Now have the ability to remove one documentation tab by adding a remove prop to the documentationtabs component.
Closes #117
> Modify documentation tabs

- src/docs/en/overview/whats-new.md
- src/docs/fr/overview/nouveautes.md
Updated What's New page to reflect changes that will be deployed on December 28
> Version 0.3.2

- src/docs/en/component/colour.md
- src/docs/en/overview/whats-new.md
- src/docs/fr/component/couleur.md
Updates to colour page (EN and FR) to better reflect choosing and creating palettes for an application. Update includes:
- Updated documentation for colour, including how to pick from swatch families and build a full UI palette
- New block elements to better display colours with hex codes
- New shades for refined Aurora Borealis swatch family and palette
- Gradient examples using Aurora Borealis swatches
> Updates to colour page

- src/docs/en/data/data-overview.md
But see also #231 
Correcting time format per https://design.gccollab.ca/content/formatting
> Proofreading

- src/docs/en/data/data-tables.md
> Proofreading edit

- src/docs/en/content/content-guidelines.md
- src/docs/en/content/formatting.md
- src/docs/en/content/system vocabulary.md
- src/docs/en/data/data-overview.md
- src/docs/en/data/scatterplots.md
- src/docs/fr/content/mise en forme du contenu.md
- src/docs/fr/data/donnees_ apercu.md
- src/docs/fr/data/donnees_ nuage de points.md
Closes issues #233 #231 #225 #227
Added information about quotation marks
Fixed headings in Content Guidelines
Small documentation fixes in data section.
> Documentation fixes

- CONTRIBUTING.md
- README.md
- src/docs/en/overview/whats-new.md
- src/docs/fr/overview/nouveautes.md
Update to README
New bullet points for updates for v.0,3.4
Closes issue: #243
> V.0.3.4 README and what's new updates

- src/components/header.js
- src/components/subnav.js
- src/pages/index.js
Added additional CSS to stop svgs appearing at 100% width on initial load.
> SVG loading size fix

- src/docs/fr/content/mise en forme du contenu.md
> Clarify note re. curly quotes

- src/docs/en/component/search.md
- src/docs/fr/component/recherche.md
Removed line about search icon from documentation in EN and FR.
> Fix in Search documentation

- src/docs/en/overview/blogs.md
- src/docs/en/overview/checklist.md
- src/docs/fr/overview/blogues.md
- src/docs/fr/overview/liste de verification.md
Fixed mistake in Blogs nav, and added Contributing doc (EN and FR) to website.
Closes #260
> Added Checklist/Contributing doc to Overview section

- src/docs/fr/content/vocabulaire du systeme.md
Small language change, for preference
> Changed "Ouvrir une session" to "Se connecter"
